---
title: "Multi-Sample Tests and Randomization Test"
author: Write your name here
output: 
   html_document:
     toc: yes
---

**In this problem, you will analyze the Stat 100 survey 3 data in Fall 2015. The csv file can be downloaded <a href="http://courses.las.illinois.edu/stat/stat100/survey/archive/Stat100_2015fall_survey03.csv" target="_blank">here</a>.. The column variables are described on <a href="http://courses.las.illinois.edu/stat/stat100/survey/archive/Stat100_2015fall_survey03.html" target="_blank">this webpage</a>. The purpose of this exercise is to find out if there is any association between happiness (a person's subjective well-being) and a person's temperament (introvert/extrovert/ambirvert).** 

###a. (2 points)

**Create box plots of `happiness` for the introverts, extroverts and ambiverts. Add the group means to the box plots.**

<span style="color:green;">Show your plots here</span>

###b. (3 points)

**Perform an F-test to determine if there are any significant differences on the reported scale of happiness among introverts, extroverts and ambiverts. (2 pts)** 

<span style="color:green;">Show your calculation here</span>

**Report the p-value and state your conclusion. (1 point)**

<span style="color:green;">Write your answer here</span>

###c. (4 points)

**Perform pairwise t-tests with Bonferroni correction to adjust the p-values. (2 pts)** 

<span style="color:green;">Show your calculation here</span>

**Determine from the adjusted p-values which pairs of groups show significant differences at the 5% level. (2 pts)**

<span style="color:green;">Write your answer here</span>

###d. (5 points) 

**Perform a randomization test by scrambling the `happiness` variable and calculate the values of R<sup>2</sup> of the scrambled data. Repeat the experiment at least 5000 times. (3 pts)**

**Note: The result of your randomization test must be *reproducible*. Therefore, you must set a seed number before calling any function involving random numbers. Use `set.seed(your UIN number)`. You can simply follow the procedure in <a href="http://courses.atlas.illinois.edu/spring2018/STAT/STAT200/RProgramming/ANOVA.html" target="_blank">this week's notes</a>. You are not required to optimize the code.**

<span style="color:green;">Show your code here</span>

**Make a histogram of these R = $\sqrt{R^2}$ and indicate the position of the original R (from the unscrambled data). (2 pt)**

<span style="color:green;">Show your plot here</span>


###e. (3 points) 

**Use the result of (d) to estimate the p-value. How does this estimated p-value compare to the one computed in part (b)?**

<span style="color:green;">Show your calculation here</span>
